### ISSUE TITLE
Add 'switch blocks source' feature

### ISSUE THREAD

**Issue by vladpolonskiy** [webarkio/wp_qoob#11]
1. Select field in the top of groups menu.  Select from libraries - which to use. It could be a file, called group_paths.json, placed into the theme folder. It will contain paths to the groups.json files from different lcoations (theme, plugin, online sources, custom sources) and will store them into options table during theme installing.
2.  New groups.json files would contain group's lists and lists of paths to block's config.json files.
3. Creating ajax methods for gathering sources and creating a basic list of groups and blocks during builder loading.

**Comment by maxazan** [comment]
Issue moved to [webarkio/qoob #8](https://github.com/webarkio/qoob/issues/8) via [**ZenHub**](https://www.zenhub.com/)
