### ISSUE TITLE
Delete "it" from all buttons "edit with qoob it"

### ISSUE THREAD

**Issue by maxazan** [webarkio/wp_qoob#14]

**Comment by jjuja** [comment]
Все поправлено. У меня есть 1 вопрос.
Если в qoob не сохранить не единого блока -> в списке страниц нет ссылки "Edit with qoob"
![image](https://cloud.githubusercontent.com/assets/8612098/18239304/0d113a0e-734d-11e6-8a12-5b245c8cab93.png)
