### ISSUE TITLE
qoob-wordpress-driver.js:134 error

### ISSUE THREAD

**Issue by Alecto** [webarkio/wp_qoob#17]
Sometimes in google chrome an error occurs on the page, created in qoob:
/wp-content/plugins/qoob/qoob-wordpress-driver.js:134 error

https://image.prntscr.com/image/RQL2foD8SgSXrp5AG0A1Ag.png

**Comment by portapro** [comment]
Thanks for using Qoob and your feedback! 
The issue has been solved. We'll update Qoob on WP repository shortly. 
Have a good day!
