### ISSUE TITLE
Qoob dont support Handlebars {{sum ...}}, {{multiply ..}}

### ISSUE THREAD

**Issue by Alecto** [webarkio/wp_qoob#20]
Qoob uses Handlebars in templates, but why it dont support Handlebars Basics?

For example:
{{sum 1 2 3}} and {{multiply 3 2}}

Often there is a need to pass parameters from options to tag attributes using mathematical operations.

Or how to do opearation:
{{order}} * {{number-parameter}}
?

**Comment by kaganvmz** [comment]
Handlebars does not include Built-In Helpers such as {{sum}} and {{multiply}}. You can see all Built-In Helpers here - http://handlebarsjs.com/builtin_helpers.html. As for operation * you can try helper math.

**Comment by kaganvmz** [comment]
If you need some additional helper you can create a pull request in repository https://github.com/webarkio/qoob in file qoob/libs/handlebars-helper.js or you can wait untill  helpers to be added in the next version.

**Comment by Alecto** [comment]
Thank you, I will wait next version.

**Comment by portapro** [comment]
Hi! We've added standard math opertaions to Handlebars in a new version 2.0.7. Wishes

**Comment by Alecto** [comment]
thank U!!!!!

**Comment by Alecto** [comment]
Works great! exactly what was lacking!
thank you very much!!!

**Comment by Alecto** [comment]
dont no why, but i try
{{sum 2 3}} = 0 - look like dosent work
but 
{{multiply 2 3}} = 6 - works

UPD:
{{math 1 "+" 2}} - works
:)
