### ISSUE TITLE
Uncaught Error: The snippet preview requires a valid target element

### ISSUE THREAD

**Issue by Alecto** [webarkio/wp_qoob#21]
Any Qoob page in edit mode works with errors shown in the console.
https://image.prntscr.com/image/igrk_HtsRQutm2W7NVuEqw.png

In this case, if the page has elements with javascript, then such elements are either not displayed at all (animation, carousel, etc.), or are displayed incorrectly.

**Comment by kaganvmz** [comment]
Alecto, are you using Yoast SEO plugin?

**Comment by Alecto** [comment]
Yep.

**Comment by portapro** [comment]
@Alecto We've fixed the bug in the new version 3.0 Please update
