### ISSUE TITLE
qoob doesnt work properly on HTTPS sites

### ISSUE THREAD

**Issue by Alecto** [webarkio/wp_qoob#23]
at one test site, accessible via protocol HTTP qoob works properly.

at other site, accessible via httpS - qoob doesnt work properly (not all blocks work):
1 - it is impossible to add more than one section from different tabs (click on them, but they are not added).
2 - if one section is added - SAVE is working, if one more added - SAVE not ending.
3 - sometimes it is generally impossible to add sections (click on them, but look like they are not added).

http://savepic.net/9879936.gif

and many errors in console:
https://image.prntscr.com/image/YBBgIvmrSjuEnjAyvey7_Q.png

Mixed Content: The page at 'https://site.name/wp-admin/post.php?post=2&action=qoob#index' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://webark.com/qoob/blocks/default/media/config.json'. This request has been blocked; the content must be served over HTTPS.

Can't apply mask '%block_url(assets)%/' for block 'qoob_video' in lib 'Default'. Block 'assets' not found in 'Default'.

The problem with some default blocks built into the qoob.
For me it is uncritical, since I do not use the built-in default blocks.
Perhaps the problem will be solved if you open access to the same address by https.

PS: look like problems with blocks, that use block_url mask in code.

**Comment by Alecto** [comment]
developers, is it really impossible to solve the problem ?!
or do you think that no one uses https sites?

**Comment by portapro** [comment]
Hi! Unfortunately we couldn't fix this bug earlier, because we had lots of things to work on. Currently we're trying to sort it out. Thanks for using qoob. Have a nice day!

**Comment by Alecto** [comment]
thanks for your reply.
I previously tested the qoob.
I really liked it and I decided to make a couple of landings on it.
but, unfortunately, qoob does not work on any https site at all (I do not create sites on http).
therefore there was a question: is it worth waiting for a bug fix.

**Comment by portapro** [comment]
Are you using default blocks in your project? The temporary solution for this issue might be deleting default blocks from plugins - qoob - qoob - blocks - lib.json such as assets, qoob_video_v2, qoob_video. On our part we'll try to solve this problem ASAP. Cheers.

**Comment by Alecto** [comment]
I just tested the standard blocks, but I do not use them.

I can add my blocks to the page, but because of the error they can not be changed:
https://image.prntscr.com/image/zfEN8l-tTH6CZGK24_fTpw.png
qoob-storage.js:182 Uncaught TypeError: Cannot read property 'assets' of undefined
    at QoobStorage.getAssets (qoob-storage.js:182)
    at n.initialize (field-icon.js:25)
https://github.com/webarkio/wp_qoob/issues/24

**Comment by dejury** [comment]
Would love to see a fix for this issue too 👍 It is currently not easy for me to switch to http.

**Comment by portapro** [comment]
@dejury, @Alecto 
Sorry, guys, for our late reply and thanks for using our qoob. We've fixed the issue with https. You can update to the version 2.0.8. If the issue still exists please inform us. Cheers.

**Comment by Alecto** [comment]
I check on all sites while it works. Thank you!
