### ISSUE TITLE
Conflict with Polylang

### ISSUE THREAD

**Issue by dimasp2ro** [webarkio/wp_qoob#26]
Hi there!

As I understood, it's because Polylang alter the global function with a ajaxPrefilter.
Can you help to fix it?

![image](https://user-images.githubusercontent.com/19273024/32020476-fe3e40f2-b9d8-11e7-8bb4-36360be5f595.png)

**Comment by kaganvmz** [comment]
Hi. Where did these errors appear?

**Comment by dimasp2ro** [comment]
When I'm trying to change the page with builder

**Comment by portapro** [comment]
@dimasp2ro  We've fixed the bug in the new version 3.0.1. Please update
