### ISSUE TITLE
Loading stuck on 85% on all pages

### ISSUE THREAD

**Issue by vladsar** [webarkio/wp_qoob#27]
WordPress version 4.9.4
Tried to remove default blocks, to re-install... But does not work.
I try it on my localhost (xampp)
![image](https://user-images.githubusercontent.com/16686132/35923743-8ed9a08a-0c3a-11e8-966c-9c4e55f4e606.png)

No error in console

**Comment by portapro** [comment]
@vladsar Hi! Can you provide us with more details, please? What did you re-install? And how did you remove the blocks? Can you send us a screenshot of your console? Thanks

**Comment by vladsar** [comment]
I'm sorry. It was my fault. I removed `the_content();`
Great builder, thanks for your work.
