### ISSUE TITLE
requested an insecure resource

### ISSUE THREAD

**Issue by phamap** [webarkio/wp_qoob#29]
Mixed Content: The page at 'https://vivaveggie.avmthemes.ru/wp-admin/post.php?post=256&action=qoob' was loaded over HTTPS, but requested an insecure resource 'http://vivaveggie.avmthemes.ru/about-us/?qoob=true'. This request has been blocked; the content must be served over HTTPS.

**Comment by phamap** [comment]
Hi, I get this error when I create a new page with qoob. How to fix it?

**Comment by phamap** [comment]
Qoob Version 3.0.1

**Comment by kaganvmz** [comment]
Hello. You have https and http request please use only one of it.
