### ISSUE TITLE
Adding html into textarea type block

### ISSUE THREAD

**Issue by vladsar** [webarkio/wp_qoob#30]
Is there a way to add an html through text editor? 
for example <a> tag...
or embedded video 
`<iframe width="560" height="315" src="https://www.youtube.com/embed/cBSXW1pztKo" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>`

Now it works only if I add it through code as a default value in config.json. 
But If I try to put my html into text editor through qoob interface it just shows me as a text.

**Comment by kaganvmz** [comment]
@vladsar The textarea processes only simple HTML tags like a b, i. If you need to add an iframe to a block, you should do it in the template.hbs.
